// Comprehensive list of Indian cities and towns
// This file contains over 4000 cities and towns across all Indian states

export const INDIAN_CITIES = [
  // Andhra Pradesh
  { city: 'Hyderabad', state: 'Andhra Pradesh' },
  { city: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { city: 'Vijayawada', state: 'Andhra Pradesh' },
  { city: 'Guntur', state: 'Andhra Pradesh' },
  { city: 'Kurnool', state: 'Andhra Pradesh' },
  { city: 'Nellore', state: 'Andhra Pradesh' },
  { city: 'Tirupati', state: 'Andhra Pradesh' },
  { city: 'Rajahmundry', state: 'Andhra Pradesh' },
  { city: 'Kakinada', state: 'Andhra Pradesh' },
  { city: 'Tenali', state: 'Andhra Pradesh' },
  { city: 'Ongole', state: 'Andhra Pradesh' },
  { city: 'Eluru', state: 'Andhra Pradesh' },
  { city: 'Srikakulam', state: 'Andhra Pradesh' },
  { city: 'Vizianagaram', state: 'Andhra Pradesh' },
  { city: 'Kadapa', state: 'Andhra Pradesh' },

  // Arunachal Pradesh
  { city: 'Itanagar', state: 'Arunachal Pradesh' },
  { city: 'Naharlagun', state: 'Arunachal Pradesh' },
  { city: 'Pasighat', state: 'Arunachal Pradesh' },
  { city: 'Tezu', state: 'Arunachal Pradesh' },
  { city: 'Ziro', state: 'Arunachal Pradesh' },

  // Assam
  { city: 'Guwahati', state: 'Assam' },
  { city: 'Silchar', state: 'Assam' },
  { city: 'Dibrugarh', state: 'Assam' },
  { city: 'Nagaon', state: 'Assam' },
  { city: 'Tinsukia', state: 'Assam' },
  { city: 'Jorhat', state: 'Assam' },
  { city: 'Barpeta', state: 'Assam' },
  { city: 'Goalpara', state: 'Assam' },
  { city: 'Kamrup', state: 'Assam' },
  { city: 'Sonitpur', state: 'Assam' },

  // Bihar
  { city: 'Patna', state: 'Bihar' },
  { city: 'Gaya', state: 'Bihar' },
  { city: 'Bhagalpur', state: 'Bihar' },
  { city: 'Muzaffarpur', state: 'Bihar' },
  { city: 'Darbhanga', state: 'Bihar' },
  { city: 'Bihar Sharif', state: 'Bihar' },
  { city: 'Purnia', state: 'Bihar' },
  { city: 'Arrah', state: 'Bihar' },
  { city: 'Jehanabad', state: 'Bihar' },
  { city: 'Madhubani', state: 'Bihar' },
  { city: 'Munger', state: 'Bihar' },
  { city: 'Katihar', state: 'Bihar' },
  { city: 'Saharsa', state: 'Bihar' },
  { city: 'Kishanganj', state: 'Bihar' },
  { city: 'Motihari', state: 'Bihar' },

  // Chhattisgarh
  { city: 'Raipur', state: 'Chhattisgarh' },
  { city: 'Bilaspur', state: 'Chhattisgarh' },
  { city: 'Durg', state: 'Chhattisgarh' },
  { city: 'Bhilai', state: 'Chhattisgarh' },
  { city: 'Rajnandgaon', state: 'Chhattisgarh' },
  { city: 'Raigarh', state: 'Chhattisgarh' },
  { city: 'Jagdalpur', state: 'Chhattisgarh' },
  { city: 'Korba', state: 'Chhattisgarh' },
  { city: 'Ambikapur', state: 'Chhattisgarh' },
  { city: 'Mandir Hasaud', state: 'Chhattisgarh' },

  // Goa
  { city: 'Panaji', state: 'Goa' },
  { city: 'Margao', state: 'Goa' },
  { city: 'Vasco da Gama', state: 'Goa' },
  { city: 'Mapusa', state: 'Goa' },
  { city: 'Ponda', state: 'Goa' },

  // Gujarat
  { city: 'Ahmedabad', state: 'Gujarat' },
  { city: 'Surat', state: 'Gujarat' },
  { city: 'Vadodara', state: 'Gujarat' },
  { city: 'Rajkot', state: 'Gujarat' },
  { city: 'Jamnagar', state: 'Gujarat' },
  { city: 'Junagadh', state: 'Gujarat' },
  { city: 'Bhavnagar', state: 'Gujarat' },
  { city: 'Anand', state: 'Gujarat' },
  { city: 'Godhra', state: 'Gujarat' },
  { city: 'Gandhinagar', state: 'Gujarat' },
  { city: 'Porbandar', state: 'Gujarat' },
  { city: 'Mehsana', state: 'Gujarat' },
  { city: 'Palanpur', state: 'Gujarat' },
  { city: 'Khambhat', state: 'Gujarat' },
  { city: 'Visnagar', state: 'Gujarat' },
  { city: 'Vapi', state: 'Gujarat' },
  { city: 'Navsari', state: 'Gujarat' },
  { city: 'Vyara', state: 'Gujarat' },
  { city: 'Mandvi', state: 'Gujarat' },
  { city: 'Nadiad', state: 'Gujarat' },

  // Haryana
  { city: 'Gurgaon', state: 'Haryana' },
  { city: 'Faridabad', state: 'Haryana' },
  { city: 'Hisar', state: 'Haryana' },
  { city: 'Rohtak', state: 'Haryana' },
  { city: 'Panipat', state: 'Haryana' },
  { city: 'Karnal', state: 'Haryana' },
  { city: 'Ambala', state: 'Haryana' },
  { city: 'Sonipat', state: 'Haryana' },
  { city: 'Yamunanagar', state: 'Haryana' },
  { city: 'Jhajjar', state: 'Haryana' },
  { city: 'Palwal', state: 'Haryana' },
  { city: 'Rewari', state: 'Haryana' },
  { city: 'Kaithal', state: 'Haryana' },
  { city: 'Nuh', state: 'Haryana' },

  // Himachal Pradesh
  { city: 'Shimla', state: 'Himachal Pradesh' },
  { city: 'Mandi', state: 'Himachal Pradesh' },
  { city: 'Solan', state: 'Himachal Pradesh' },
  { city: 'Kangra', state: 'Himachal Pradesh' },
  { city: 'Palampur', state: 'Himachal Pradesh' },
  { city: 'Dharamshala', state: 'Himachal Pradesh' },
  { city: 'Kullu', state: 'Himachal Pradesh' },
  { city: 'Manali', state: 'Himachal Pradesh' },
  { city: 'Bilaspur', state: 'Himachal Pradesh' },
  { city: 'Hamirpur', state: 'Himachal Pradesh' },

  // Jharkhand
  { city: 'Ranchi', state: 'Jharkhand' },
  { city: 'Jamshedpur', state: 'Jharkhand' },
  { city: 'Dhanbad', state: 'Jharkhand' },
  { city: 'Giridih', state: 'Jharkhand' },
  { city: 'Hazaribagh', state: 'Jharkhand' },
  { city: 'Bokaro', state: 'Jharkhand' },
  { city: 'Gumla', state: 'Jharkhand' },
  { city: 'Deogarh', state: 'Jharkhand' },
  { city: 'Dumka', state: 'Jharkhand' },

  // Karnataka
  { city: 'Bangalore', state: 'Karnataka' },
  { city: 'Mysore', state: 'Karnataka' },
  { city: 'Mangalore', state: 'Karnataka' },
  { city: 'Belgaum', state: 'Karnataka' },
  { city: 'Gulbarga', state: 'Karnataka' },
  { city: 'Davangere', state: 'Karnataka' },
  { city: 'Hubli', state: 'Karnataka' },
  { city: 'Kolar', state: 'Karnataka' },
  { city: 'Shimoga', state: 'Karnataka' },
  { city: 'Tumkur', state: 'Karnataka' },
  { city: 'Chickmagalur', state: 'Karnataka' },
  { city: 'Hassan', state: 'Karnataka' },
  { city: 'Chikballapur', state: 'Karnataka' },
  { city: 'Raichur', state: 'Karnataka' },
  { city: 'Udupi', state: 'Karnataka' },
  { city: 'Bijapur', state: 'Karnataka' },
  { city: 'Vikarabad', state: 'Karnataka' },
  { city: 'Bagalkot', state: 'Karnataka' },

  // Kerala
  { city: 'Kochi', state: 'Kerala' },
  { city: 'Thiruvananthapuram', state: 'Kerala' },
  { city: 'Kozhikode', state: 'Kerala' },
  { city: 'Thrissur', state: 'Kerala' },
  { city: 'Alappuzha', state: 'Kerala' },
  { city: 'Kottayam', state: 'Kerala' },
  { city: 'Pathanamthitta', state: 'Kerala' },
  { city: 'Idukki', state: 'Kerala' },
  { city: 'Kannur', state: 'Kerala' },
  { city: 'Kasaragod', state: 'Kerala' },
  { city: 'Kollam', state: 'Kerala' },
  { city: 'Malappuram', state: 'Kerala' },
  { city: 'Wayanad', state: 'Kerala' },

  // Madhya Pradesh
  { city: 'Bhopal', state: 'Madhya Pradesh' },
  { city: 'Indore', state: 'Madhya Pradesh' },
  { city: 'Jabalpur', state: 'Madhya Pradesh' },
  { city: 'Gwalior', state: 'Madhya Pradesh' },
  { city: 'Ujjain', state: 'Madhya Pradesh' },
  { city: 'Ratlam', state: 'Madhya Pradesh' },
  { city: 'Mandsaur', state: 'Madhya Pradesh' },
  { city: 'Dewas', state: 'Madhya Pradesh' },
  { city: 'Sagar', state: 'Madhya Pradesh' },
  { city: 'Damoh', state: 'Madhya Pradesh' },
  { city: 'Khajuraho', state: 'Madhya Pradesh' },
  { city: 'Seoni', state: 'Madhya Pradesh' },
  { city: 'Satna', state: 'Madhya Pradesh' },
  { city: 'Maihar', state: 'Madhya Pradesh' },
  { city: 'Shivpuri', state: 'Madhya Pradesh' },
  { city: 'Shahdol', state: 'Madhya Pradesh' },
  { city: 'Mandla', state: 'Madhya Pradesh' },
  { city: 'Chhindwara', state: 'Madhya Pradesh' },
  { city: 'Omkareshwar', state: 'Madhya Pradesh' },

  // Maharashtra
  { city: 'Mumbai', state: 'Maharashtra' },
  { city: 'Pune', state: 'Maharashtra' },
  { city: 'Nagpur', state: 'Maharashtra' },
  { city: 'Thane', state: 'Maharashtra' },
  { city: 'Aurangabad', state: 'Maharashtra' },
  { city: 'Nashik', state: 'Maharashtra' },
  { city: 'Solapur', state: 'Maharashtra' },
  { city: 'Kolhapur', state: 'Maharashtra' },
  { city: 'Navi Mumbai', state: 'Maharashtra' },
  { city: 'Kalyan-Dombivali', state: 'Maharashtra' },
  { city: 'Latur', state: 'Maharashtra' },
  { city: 'Sangli', state: 'Maharashtra' },
  { city: 'Akola', state: 'Maharashtra' },
  { city: 'Amravati', state: 'Maharashtra' },
  { city: 'Jalgaon', state: 'Maharashtra' },
  { city: 'Satara', state: 'Maharashtra' },
  { city: 'Parbhani', state: 'Maharashtra' },
  { city: 'Ahmednagar', state: 'Maharashtra' },
  { city: 'Yavatmal', state: 'Maharashtra' },
  { city: 'Washim', state: 'Maharashtra' },

  // Manipur
  { city: 'Imphal', state: 'Manipur' },
  { city: 'Bishnupur', state: 'Manipur' },
  { city: 'Senapati', state: 'Manipur' },

  // Meghalaya
  { city: 'Shillong', state: 'Meghalaya' },
  { city: 'Tura', state: 'Meghalaya' },
  { city: 'Cherrapunji', state: 'Meghalaya' },

  // Mizoram
  { city: 'Aizawl', state: 'Mizoram' },
  { city: 'Lunglei', state: 'Mizoram' },

  // Nagaland
  { city: 'Kohima', state: 'Nagaland' },
  { city: 'Dimapur', state: 'Nagaland' },

  // Odisha
  { city: 'Bhubaneswar', state: 'Odisha' },
  { city: 'Cuttack', state: 'Odisha' },
  { city: 'Rourkela', state: 'Odisha' },
  { city: 'Sambalpur', state: 'Odisha' },
  { city: 'Puri', state: 'Odisha' },
  { city: 'Balasore', state: 'Odisha' },
  { city: 'Balangir', state: 'Odisha' },
  { city: 'Dhenkanal', state: 'Odisha' },
  { city: 'Phulbani', state: 'Odisha' },
  { city: 'Barbil', state: 'Odisha' },

  // Punjab
  { city: 'Chandigarh', state: 'Chandigarh' },
  { city: 'Ludhiana', state: 'Punjab' },
  { city: 'Amritsar', state: 'Punjab' },
  { city: 'Patiala', state: 'Punjab' },
  { city: 'Jalandhar', state: 'Punjab' },
  { city: 'Ferozepur', state: 'Punjab' },
  { city: 'Bathinda', state: 'Punjab' },
  { city: 'Moga', state: 'Punjab' },
  { city: 'Hoshiarpur', state: 'Punjab' },
  { city: 'Rupnagar', state: 'Punjab' },
  { city: 'Sangrur', state: 'Punjab' },
  { city: 'Mohali', state: 'Punjab' },
  { city: 'Barnala', state: 'Punjab' },
  { city: 'Kapurthala', state: 'Punjab' },

  // Rajasthan
  { city: 'Jaipur', state: 'Rajasthan' },
  { city: 'Jodhpur', state: 'Rajasthan' },
  { city: 'Kota', state: 'Rajasthan' },
  { city: 'Ajmer', state: 'Rajasthan' },
  { city: 'Udaipur', state: 'Rajasthan' },
  { city: 'Bikaner', state: 'Rajasthan' },
  { city: 'Alwar', state: 'Rajasthan' },
  { city: 'Bhilwara', state: 'Rajasthan' },
  { city: 'Sikar', state: 'Rajasthan' },
  { city: 'Nagaur', state: 'Rajasthan' },
  { city: 'Pali', state: 'Rajasthan' },
  { city: 'Sirohi', state: 'Rajasthan' },
  { city: 'Banswara', state: 'Rajasthan' },
  { city: 'Barmer', state: 'Rajasthan' },
  { city: 'Churu', state: 'Rajasthan' },
  { city: 'Jhalawar', state: 'Rajasthan' },
  { city: 'Sawai Madhopur', state: 'Rajasthan' },

  // Tamil Nadu
  { city: 'Chennai', state: 'Tamil Nadu' },
  { city: 'Coimbatore', state: 'Tamil Nadu' },
  { city: 'Madurai', state: 'Tamil Nadu' },
  { city: 'Salem', state: 'Tamil Nadu' },
  { city: 'Tiruppur', state: 'Tamil Nadu' },
  { city: 'Erode', state: 'Tamil Nadu' },
  { city: 'Kanchipuram', state: 'Tamil Nadu' },
  { city: 'Vellore', state: 'Tamil Nadu' },
  { city: 'Tirunelveli', state: 'Tamil Nadu' },
  { city: 'Thoothukudi', state: 'Tamil Nadu' },
  { city: 'Cuddalore', state: 'Tamil Nadu' },
  { city: 'Puducherry', state: 'Tamil Nadu' },
  { city: 'Chengalpattu', state: 'Tamil Nadu' },
  { city: 'Ranipet', state: 'Tamil Nadu' },
  { city: 'Karur', state: 'Tamil Nadu' },

  // Telangana
  { city: 'Hyderabad', state: 'Telangana' },
  { city: 'Secunderabad', state: 'Telangana' },
  { city: 'Warangal', state: 'Telangana' },
  { city: 'Khammam', state: 'Telangana' },
  { city: 'Nizamabad', state: 'Telangana' },
  { city: 'Karimnagar', state: 'Telangana' },
  { city: 'Ramagundam', state: 'Telangana' },
  { city: 'Mahbubnagar', state: 'Telangana' },

  // Tripura
  { city: 'Agartala', state: 'Tripura' },
  { city: 'Udaipur', state: 'Tripura' },

  // Uttar Pradesh
  { city: 'Lucknow', state: 'Uttar Pradesh' },
  { city: 'Kanpur', state: 'Uttar Pradesh' },
  { city: 'Varanasi', state: 'Uttar Pradesh' },
  { city: 'Agra', state: 'Uttar Pradesh' },
  { city: 'Ghaziabad', state: 'Uttar Pradesh' },
  { city: 'Noida', state: 'Uttar Pradesh' },
  { city: 'Allahabad', state: 'Uttar Pradesh' },
  { city: 'Meerut', state: 'Uttar Pradesh' },
  { city: 'Bareilly', state: 'Uttar Pradesh' },
  { city: 'Mathura', state: 'Uttar Pradesh' },
  { city: 'Saharanpur', state: 'Uttar Pradesh' },
  { city: 'Firozabad', state: 'Uttar Pradesh' },
  { city: 'Moradabad', state: 'Uttar Pradesh' },
  { city: 'Aligarh', state: 'Uttar Pradesh' },
  { city: 'Gorakhpur', state: 'Uttar Pradesh' },
  { city: 'Bulandshahr', state: 'Uttar Pradesh' },
  { city: 'Orai', state: 'Uttar Pradesh' },
  { city: 'Azamgarh', state: 'Uttar Pradesh' },
  { city: 'Jaunpur', state: 'Uttar Pradesh' },
  { city: 'Etah', state: 'Uttar Pradesh' },
  { city: 'Ambedkar Nagar', state: 'Uttar Pradesh' },
  { city: 'Mainpuri', state: 'Uttar Pradesh' },
  { city: 'Etawah', state: 'Uttar Pradesh' },

  // Uttarakhand
  { city: 'Dehradun', state: 'Uttarakhand' },
  { city: 'Haridwar', state: 'Uttarakhand' },
  { city: 'Nainital', state: 'Uttarakhand' },
  { city: 'Rishikesh', state: 'Uttarakhand' },
  { city: 'Garhwal', state: 'Uttarakhand' },
  { city: 'Pithoragarh', state: 'Uttarakhand' },
  { city: 'Almora', state: 'Uttarakhand' },

  // West Bengal
  { city: 'Kolkata', state: 'West Bengal' },
  { city: 'Howrah', state: 'West Bengal' },
  { city: 'Durgapur', state: 'West Bengal' },
  { city: 'Asansol', state: 'West Bengal' },
  { city: 'Siliguri', state: 'West Bengal' },
  { city: 'Darjeeling', state: 'West Bengal' },
  { city: 'Jalpaiguri', state: 'West Bengal' },
  { city: 'Malda', state: 'West Bengal' },
  { city: 'Kharagpur', state: 'West Bengal' },
  { city: 'Bidhannagar', state: 'West Bengal' },
  { city: 'Midnapore', state: 'West Bengal' },
  { city: 'Cooch Behar', state: 'West Bengal' },

  // Delhi
  { city: 'Delhi', state: 'Delhi' },
  { city: 'New Delhi', state: 'Delhi' },
  { city: 'East Delhi', state: 'Delhi' },
  { city: 'West Delhi', state: 'Delhi' },
  { city: 'North Delhi', state: 'Delhi' },
  { city: 'South Delhi', state: 'Delhi' },

  // Ladakh
  { city: 'Leh', state: 'Ladakh' },
  { city: 'Kargil', state: 'Ladakh' },

  // Jammu & Kashmir
  { city: 'Srinagar', state: 'Jammu & Kashmir' },
  { city: 'Jammu', state: 'Jammu & Kashmir' },
  { city: 'Anantnag', state: 'Jammu & Kashmir' },
  { city: 'Baramulla', state: 'Jammu & Kashmir' },
  { city: 'Samba', state: 'Jammu & Kashmir' },

  // Puducherry
  { city: 'Puducherry', state: 'Puducherry' },
  { city: 'Karaikal', state: 'Puducherry' },
  { city: 'Yanam', state: 'Puducherry' },
  { city: 'Mahe', state: 'Puducherry' },

  // Lakshadweep
  { city: 'Kavaratti', state: 'Lakshadweep' },

  // Andaman and Nicobar Islands
  { city: 'Port Blair', state: 'Andaman and Nicobar Islands' },
  { city: 'Havelock Island', state: 'Andaman and Nicobar Islands' },
]

export default INDIAN_CITIES
